export const QUIZ = {
    SET_CURRENT_ANSWER : 'SET_CURRENT_ANSWER',
    SET_CURRENT_QUESTION : 'SET_CURRENT_QUESTION',
    SET_ERROR : 'SET_ERROR',
    SET_SHOW_RESULTS : 'SET_SHOW_RESULTS',
    SET_IS_AUTH: 'SET_IS_AUTH',
    SET_ANSWERS : 'SET_ANSWERS',
    SET_CORRECT_ANSWERS: 'SET_CORRECT_ANSWERS',
    SET_QUESTIONS: 'SET_QUESTIONS',
    SET_COURSES_LIST: 'SET_COURSES_LIST',
    SET_EXACT_QUESTION: 'SET_EXACT_QUESTION',
    SET_USER_AUTH: 'SET_USER_AUTH', 
    RESET_QUIZ : 'RESET_QUIZ',
}
